import { CON_CLIENTI, NON_PRIVATI, RAMI_PRODOTTI, type Blocco } from "./tipi.ts";

const FATTURATO = [
  { value: "<1k", label: "Meno di 1.000 €" },
  { value: "1-3k", label: "1.000–3.000 €" },
  { value: "3-5k", label: "3.000–5.000 €" },
  { value: "5-10k", label: "5.000–10.000 €" },
  { value: "10k+", label: "Oltre 10.000 €" },
];

/** Blocco A «Il tuo lavoro e la tua offerta»: lo vedono tutti, cambiano le versioni. */
export const BLOCCO_A: Blocco = {
  id: "A_offerta",
  chiave: "A",
  titolo: "Il tuo lavoro e la tua offerta",
  emoji: "🏢",
  intro: "Partiamo da quello che fai e da quello che vendi oggi. Niente risposte perfette, solo quelle vere.",
  domande: [
    {
      id: "presentazione",
      codice: "A1",
      testo: "Racconta il tuo lavoro come lo racconteresti a un nuovo socio in 2 minuti: cosa fai, per chi, da quanto tempo e perché le persone scelgono te.",
      tipo: "textarea",
      obbligatoria: true,
      opinione: true,
    },
    {
      id: "offerta_attuale",
      codice: "A2-s",
      testo: "Quali {cosa_vende_plurale} vendi oggi, a che prezzo e come funzionano? Per esempio: {esempio_listino}.",
      tipo: "textarea",
      obbligatoria: true,
      mostraSe: { ramo: ["servizi"], clienti: CON_CLIENTI },
    },
    {
      id: "offerta_attuale",
      codice: "A2-pf",
      testo: "Quali {cosa_vende_plurale} vendi? Dicci quanti ne hai, qual è il più venduto, quello su cui guadagni di più e da che prezzo a che prezzo vai.",
      tipo: "textarea",
      obbligatoria: true,
      mostraSe: { ramo: ["prodotti_fisici"], clienti: CON_CLIENTI },
    },
    {
      id: "offerta_attuale",
      codice: "A2-pd",
      testo: "Quali {cosa_vende_plurale} vendi, a che prezzo e cosa c'è dentro? Per esempio: {esempio_listino}.",
      tipo: "textarea",
      obbligatoria: true,
      mostraSe: { ramo: ["prodotti_digitali"], clienti: CON_CLIENTI },
    },
    {
      id: "offerta_attuale",
      codice: "A2-n",
      testo: "Cosa vuoi vendere e a che prezzo pensi di venderlo? Se il prezzo non lo sai ancora, scrivi «non lo so».",
      tipo: "textarea",
      obbligatoria: true,
      mostraSe: { clienti: ["nessuno"] },
    },
    {
      id: "spesa_media",
      codice: "A3",
      testo: "Quanto spende in media un {cliente} in un ordine?",
      tipo: "number",
      unita: "€",
      obbligatoria: true,
      mostraSe: { ramo: RAMI_PRODOTTI, clienti: CON_CLIENTI },
    },
    {
      id: "margine",
      codice: "A4",
      testo: "Su un prodotto medio, quanto ti resta in tasca dopo i costi? Basta una percentuale a occhio.",
      tipo: "number",
      unita: "%",
      max: 100,
      obbligatoria: false,
      mostraSe: { ramo: ["prodotti_fisici"], clienti: CON_CLIENTI },
    },
    {
      id: "fatturato_fascia",
      codice: "A5",
      testo: "Quanto hai fatturato in media al mese negli ultimi 6 mesi?",
      tipo: "select",
      obbligatoria: true,
      opzioni: FATTURATO,
      mostraSe: { clienti: CON_CLIENTI },
    },
    {
      id: "processo_vendita",
      codice: "A6-s",
      testo: "Racconta l'ultimo {cliente} che hai chiuso: dove ti ha trovato, cosa ti ha scritto, cosa è successo fino al pagamento.",
      tipo: "textarea",
      obbligatoria: true,
      mostraSe: { ramo: ["servizi"], clienti: CON_CLIENTI },
    },
    {
      id: "conversione",
      codice: "A6-s",
      testo: "E su 10 persone interessate, quante comprano?",
      tipo: "number",
      unita: "su 10",
      max: 10,
      obbligatoria: true,
      mostraSe: { ramo: ["servizi"], clienti: CON_CLIENTI },
    },
    {
      id: "processo_vendita_canali",
      codice: "A6-p",
      testo: "Come compra oggi un {cliente}?",
      tipo: "multiselect-text",
      obbligatoria: true,
      consentiAltro: true,
      opzioni: [
        { value: "sito", label: "Da solo sul sito" },
        { value: "dm", label: "Scrivendomi in DM o WhatsApp" },
        { value: "negozio", label: "In negozio" },
        { value: "marketplace", label: "Su un marketplace (Etsy, Amazon…)" },
      ],
      mostraSe: { ramo: RAMI_PRODOTTI, clienti: CON_CLIENTI },
    },
    {
      id: "ordini_mese",
      codice: "A6-p2",
      testo: "Quanti ordini fai in un mese normale?",
      tipo: "number",
      unita: "ordini",
      obbligatoria: true,
      mostraSe: { ramo: RAMI_PRODOTTI, clienti: CON_CLIENTI },
    },
    {
      id: "ritorno",
      codice: "A7-s",
      testo: "Quanto resta di solito un {cliente} con te? Torna o ti manda altre persone?",
      tipo: "textarea",
      obbligatoria: true,
      mostraSe: { ramo: ["servizi"], clienti: CON_CLIENTI },
    },
    {
      id: "ritorno",
      codice: "A7-p",
      testo: "Ogni quanto ricompra un {cliente}? Su 10 {clienti}, quanti tornano?",
      tipo: "textarea",
      obbligatoria: true,
      mostraSe: { ramo: RAMI_PRODOTTI, clienti: CON_CLIENTI },
    },
    {
      id: "capacita",
      codice: "A8-s",
      testo: "Quanti {clienti} al mese riusciresti a seguire bene, al massimo, contando anche quelli che hai già?",
      tipo: "text",
      obbligatoria: true,
      placeholder: "Un numero, anche a occhio",
      mostraSe: { ramo: ["servizi"] },
    },
    {
      id: "capacita",
      codice: "A8-pf",
      testo: "Quanti pezzi al mese riusciresti a produrre e spedire, al massimo? Quanto tempo ti serve per farne uno?",
      tipo: "textarea",
      obbligatoria: true,
      mostraSe: { ramo: ["prodotti_fisici"] },
    },
    {
      id: "consegna",
      codice: "A8-pd",
      testo: "Come arriva il prodotto al {cliente}? Per esempio una piattaforma per corsi, una email, un gruppo o una community.",
      tipo: "textarea",
      obbligatoria: true,
      mostraSe: { ramo: ["prodotti_digitali"] },
    },
    {
      id: "prove",
      codice: "A9",
      testo: "Cosa puoi dimostrare oggi?",
      tipo: "multiselect-text",
      obbligatoria: true,
      opzioni: [
        { value: "recensioni", label: "Recensioni o foto dei clienti" },
        { value: "risultati", label: "Risultati o casi di clienti" },
        { value: "numeri", label: "Numeri (clienti seguiti, pezzi venduti, anni di lavoro)" },
        { value: "titoli", label: "Titoli e certificazioni" },
        { value: "stampa", label: "Giornali, eventi, podcast" },
        { value: "niente", label: "Niente ancora" },
      ],
    },
    {
      id: "prove_testo",
      codice: "A9",
      testo: "Scrivi le prove più forti.",
      tipo: "textarea",
      obbligatoria: false,
      placeholder: "Es. 120 clienti seguiti in 4 anni, 60 recensioni a 5 stelle su Google…",
    },
    {
      id: "offerta_secondaria",
      codice: "A10",
      testo: "Oltre a quello che vendi di più, cos'altro vendi, a che prezzo e quanto pesa sul fatturato? Per esempio: «vendo anche prodotti per capelli, circa il 20% del fatturato».",
      tipo: "textarea",
      obbligatoria: true,
      mostraSe: { tipo: ["mix"] },
    },
    {
      id: "decisore",
      codice: "A11",
      testo: "Nelle aziende a cui vendi, chi decide l'acquisto? E chi altro deve dire sì?",
      tipo: "textarea",
      obbligatoria: true,
      mostraSe: { mercato: NON_PRIVATI },
    },
    {
      id: "ciclo_vendita",
      codice: "A12",
      testo: "Quanto tempo passa di solito dal primo contatto alla firma?",
      tipo: "select",
      obbligatoria: true,
      opzioni: [
        { value: "<1_settimana", label: "Meno di una settimana" },
        { value: "1-4_settimane", label: "1–4 settimane" },
        { value: "1-3_mesi", label: "1–3 mesi" },
        { value: ">3_mesi", label: "Più di 3 mesi" },
      ],
      mostraSe: { mercato: NON_PRIVATI, clienti: CON_CLIENTI },
    },
  ],
};
