import { CON_CLIENTI, PUBBLICA, RAMI_PRODOTTI, type Blocco } from "./tipi.ts";

const SENZA_CLIENTI_NASCOSTO = { clienti: CON_CLIENTI };

/** Blocco C «La tua comunicazione oggi»: quattro domande comuni, poi la versione scelta dalla 0.6. */
export const BLOCCO_C: Blocco = {
  id: "C_comunicazione",
  chiave: "C",
  titolo: "La tua comunicazione oggi",
  emoji: "📣",
  intro: "Come comunichi oggi, con i numeri veri che hai. Chi non pubblica ancora non deve inventarsi niente.",
  domande: [
    {
      id: "link_profili",
      codice: "C1",
      testo: "Link ai tuoi profili social e al sito, se ce l'hai.",
      tipo: "url-list",
      obbligatoria: false,
      placeholder: "instagram.com/tuonome",
      mostraSe: { social: ["non_pubblica"] },
    },
    {
      id: "link_profili",
      codice: "C1",
      testo: "Link ai tuoi profili social e al sito, se ce l'hai.",
      tipo: "url-list",
      obbligatoria: true,
      placeholder: "instagram.com/tuonome",
      mostraSe: { social: PUBBLICA },
    },
    {
      id: "camera_agio",
      codice: "C2",
      testo: "Quanto ti senti a tuo agio davanti alla camera, da 1 a 5?",
      tipo: "scala",
      min: 1,
      max: 5,
      obbligatoria: true,
    },
    {
      id: "vincoli_camera",
      codice: "C2",
      testo: "Hai dei limiti? Per esempio non vuoi mostrare la faccia o la voce, o il tuo lavoro ha vincoli di privacy.",
      tipo: "textarea",
      obbligatoria: false,
    },
    {
      id: "tentativi_passati",
      codice: "C3",
      testo: "Cosa hai già provato per farti conoscere online, e quanto hai speso più o meno? Com'è andata? Per esempio corsi, agenzie, pubblicità.",
      tipo: "textarea",
      obbligatoria: true,
    },
    {
      id: "riferimenti",
      codice: "C4",
      testo: "2-3 creator o professionisti che comunicano in un modo che ti piace.",
      tipo: "textarea",
      obbligatoria: true,
      placeholder: "Nomi o link",
    },
    // --- versione «non pubblico ancora» ---
    {
      id: "blocco_partenza",
      codice: "C5-z",
      testo: "Cosa ti ha fermato finora?",
      tipo: "multiselect-text",
      obbligatoria: true,
      opzioni: [
        { value: "cosa_dire", label: "Non so cosa dire" },
        { value: "camera", label: "Non mi piace stare davanti alla camera" },
        { value: "tempo", label: "Non ho tempo" },
        { value: "strumenti", label: "Non so usare gli strumenti" },
        { value: "settore", label: "Non credo che nel mio settore funzioni" },
        { value: "altro", label: "Altro" },
      ],
      mostraSe: { social: ["non_pubblica"] },
    },
    {
      id: "blocco_partenza_testo",
      codice: "C5-z",
      testo: "Raccontaci meglio.",
      tipo: "textarea",
      obbligatoria: false,
      mostraSe: { social: ["non_pubblica"] },
    },
    {
      id: "paure",
      codice: "C6-z",
      testo: "Cosa ti preoccupa di più all'idea di iniziare?",
      tipo: "textarea",
      obbligatoria: false,
      opinione: true,
      mostraSe: { social: ["non_pubblica"] },
    },
    // --- versione «pubblico già» ---
    {
      id: "collo_bottiglia",
      codice: "C5-s",
      testo: "Dove si blocca, oggi?",
      tipo: "select",
      obbligatoria: true,
      opzioni: [
        { value: "poche_views", label: "Pubblico ma faccio poche visualizzazioni" },
        { value: "views_senza_contatti", label: "Le visualizzazioni ci sono, ma quasi nessuno mi scrive" },
        { value: "contatti_senza_vendite", label: "Mi scrivono, ma pochi comprano", mostraSe: SENZA_CLIENTI_NASCOSTO },
        { value: "clienti_o_prezzi_sbagliati", label: "Vendo, ma a clienti sbagliati o a prezzi troppo bassi", mostraSe: SENZA_CLIENTI_NASCOSTO },
      ],
      mostraSe: { ramo: ["servizi"], social: PUBBLICA },
    },
    {
      id: "collo_bottiglia",
      codice: "C5-p",
      testo: "Dove si blocca, oggi?",
      tipo: "select",
      obbligatoria: true,
      opzioni: [
        { value: "poche_views", label: "Pubblico ma faccio poche visualizzazioni" },
        { value: "views_senza_contatti", label: "Le visualizzazioni ci sono, ma pochi visitano il negozio o il sito" },
        { value: "visite_senza_acquisti", label: "Visitano, ma pochi comprano" },
        { value: "nessun_ritorno", label: "Comprano una volta e non tornano", mostraSe: SENZA_CLIENTI_NASCOSTO },
        { value: "margini_bassi", label: "Vendo, ma con margini troppo bassi", mostraSe: SENZA_CLIENTI_NASCOSTO },
      ],
      mostraSe: { ramo: RAMI_PRODOTTI, social: PUBBLICA },
    },
    {
      id: "diagnosi_cliente",
      codice: "C6",
      testo: "Secondo te, perché i social oggi non ti portano i risultati che vorresti?",
      tipo: "textarea",
      obbligatoria: true,
      opinione: true,
      mostraSe: { social: PUBBLICA },
    },
    {
      id: "frequenza",
      codice: "C7",
      testo: "Quanti contenuti pubblichi a settimana, più o meno?",
      tipo: "number",
      unita: "a settimana",
      obbligatoria: true,
      mostraSe: { social: PUBBLICA },
    },
    {
      id: "contenuti_migliori",
      codice: "C8",
      testo: "I contenuti che ti hanno portato messaggi o {clienti}: link o descrizione. Se non ce ne sono, i 3 con più visualizzazioni.",
      tipo: "textarea",
      obbligatoria: true,
      mostraSe: { social: PUBBLICA },
    },
    {
      id: "follower",
      codice: "C9",
      testo: "Quanti follower hai in tutto, anche a occhio?",
      tipo: "number",
      unita: "follower",
      obbligatoria: false,
      mostraSe: { social: PUBBLICA },
    },
    {
      id: "views_medie",
      codice: "C9",
      testo: "Visualizzazioni medie di un contenuto negli ultimi 30 giorni, anche a occhio.",
      tipo: "number",
      unita: "views",
      obbligatoria: false,
      mostraSe: { social: PUBBLICA },
    },
    {
      id: "clienti_da_social",
      codice: "C10",
      testo: "Quanti {clienti} al mese ti arrivano dai social, più o meno?",
      tipo: "number",
      unita: "al mese",
      obbligatoria: true,
      mostraSe: { social: ["porta_clienti"] },
    },
    {
      id: "priorita_crescita",
      codice: "C11",
      testo: "Cosa vuoi migliorare adesso?",
      tipo: "select",
      obbligatoria: true,
      opzioni: [
        { value: "piu_clienti", label: "Più {clienti}" },
        { value: "clienti_migliori", label: "{clienti} migliori" },
        { value: "prezzi_alti", label: "Prezzi più alti" },
        { value: "meno_tempo", label: "Meno tempo speso sui social" },
      ],
      mostraSe: { social: ["porta_clienti"] },
    },
  ],
};
