/**
 * Informativa sul trattamento dei dati personali (art. 13 Reg. UE 2016/679).
 * Sta su una pagina pubblica del sito (URL_INFORMATIVA): il cliente la apre
 * dal primo passo del modulo e conferma di averne preso visione; il contratto
 * la richiama con il suo indirizzo. Se cambia, aggiorna VERSIONE_INFORMATIVA.
 *
 * I tempi di conservazione del punto 6 sono impegni veri: chi gestisce il
 * sistema deve poi cancellare davvero i dati alle scadenze indicate.
 */

import { blocchi } from "./documento.ts";
import { FORNITORE as F } from "./fornitore.ts";
import type { Blocco } from "./tipi.ts";

export const VERSIONE_INFORMATIVA = "2026.10";

/** Percorso e indirizzo della pagina pubblica con l'informativa. */
export const PERCORSO_INFORMATIVA = "/informativa-privacy";
export const URL_INFORMATIVA = `https://${F.sito}${PERCORSO_INFORMATIVA}`;

export function informativa(): Blocco[] {
  return blocchi(`
## Informativa sul trattamento dei dati personali
> Art. 13 del Regolamento (UE) 2016/679. Versione ${VERSIONE_INFORMATIVA}. In questa informativa «Programma» è il programma formativo UPSCALE; «Community» comprende la community su Skool, il gruppo WhatsApp e le chiamate di gruppo; «Sito» è l'area clienti di ${F.sito}; «Cliente» è chi acquista il Programma.
**1. Chi tratta i dati.** Titolare del trattamento è ${F.nome}, con sede in ${F.sede}, P.IVA ${F.partitaIva}, email ${F.email}, PEC ${F.pec}.
**2. Quali dati.** Dati anagrafici e di contatto (nome, cognome, luogo e data di nascita, indirizzo, codice fiscale, eventuale partita IVA e dati della società, email, telefono, profili social); dati di fatturazione e di pagamento; la firma tracciata sullo schermo, di cui si conserva solo la forma del segno (non vengono registrati tempi, pressione o inclinazione; la firma non è confrontata con altre firme né usata per riconoscere il Cliente, e non è trattata come dato biometrico), insieme a data e ora della firma, indirizzo IP, dispositivo e browser usati e impronta informatica del testo firmato; data e ora di apertura dell'invito e di conferma di lettura di questa informativa; le informazioni che il Cliente condivide durante il Programma (risposte ai questionari, informazioni sulla propria attività, messaggi); immagine e voce nelle registrazioni delle chiamate. Non servono dati sulla salute né altre categorie particolari di dati (art. 9 del Regolamento): il Cliente non deve inserirli nei questionari né condividerli nelle chiamate registrate. Il modulo conserva nel browser, solo per la sessione, una bozza dei dati inseriti, cancellata alla firma.
**3. Perché e su quale base giuridica.** I dati sono trattati: (a) per concludere ed eseguire il contratto: accessi, Community, chiamate, registrazione e trascrizione delle chiamate, accesso del Cliente alle registrazioni, assistenza (art. 6, par. 1, lett. b del Regolamento); (b) per rendere le registrazioni delle chiamate di gruppo visibili agli altri partecipanti al Programma, anche a quelli che entrano dopo e anche dopo la fine del Programma del Cliente, perché chi non ha seguito la diretta possa recuperarla (legittimo interesse, art. 6, par. 1, lett. f; chi non vuole comparire non partecipa in diretta e guarda la registrazione); (c) per registrare le chiamate individuali, che restano al solo Cliente e al Titolare (art. 6, par. 1, lett. b) e non sono messe a disposizione degli altri partecipanti senza un consenso separato e revocabile (art. 6, par. 1, lett. a); (d) per adempiere agli obblighi di legge, in particolare fiscali e contabili (art. 6, par. 1, lett. c); (e) per conservare la prova della firma (data, ora, indirizzo IP, dispositivo, impronta del testo firmato) e accertare, esercitare o difendere un diritto in giudizio (legittimo interesse, art. 6, par. 1, lett. f): questi dati sono usati solo in caso di contestazione; (f) per elaborare con strumenti di intelligenza artificiale le informazioni fornite dal Cliente (risposte ai questionari, riassunti delle chiamate, profili social indicati) e preparare documenti di lavoro e suggerimenti per il Programma (legittimo interesse, art. 6, par. 1, lett. f: offrire un servizio personalizzato; se il Cliente si oppone, il Titolare smette di usare questi strumenti sui suoi dati); (g) per l'uso pubblico di testimonianze, risultati o immagini del Cliente, solo con un consenso separato, chiesto di volta in volta e sempre revocabile (art. 6, par. 1, lett. a). I dati dei punti (a) e (d) sono necessari, compresi data, ora, indirizzo IP e dispositivo raccolti alla firma: senza, il contratto non può essere concluso. I profili social e i consensi dei punti (c) e (g) sono facoltativi e non fornirli non ha conseguenze.
**4. A chi arrivano.** I dati sono trattati dal Titolare e dai collaboratori che ha autorizzato, e dai fornitori dei servizi usati per erogare il Programma, che agiscono come responsabili del trattamento o come titolari autonomi: la piattaforma della community e delle lezioni (Skool); la messaggistica (WhatsApp); i servizi di videochiamata, registrazione e trascrizione delle chiamate (tra cui Fathom); l'hosting e il database del Sito (Cloudflare, Supabase); i servizi di intelligenza artificiale con cui gli strumenti del Sito elaborano le informazioni fornite dal Cliente (Anthropic: i dati inviati non sono usati per addestrarne i modelli); posta elettronica, calendario e strumenti di organizzazione del lavoro (Google, Notion, Telegram); il consulente fiscale, le banche e gli istituti di pagamento; l'Agenzia delle Entrate per la fatturazione elettronica. Le registrazioni delle chiamate di gruppo, con immagine, voce e interventi del Cliente, sono visibili agli altri partecipanti al Programma, tenuti alla riservatezza (art. 8 del contratto). Nel gruppo WhatsApp il nome e il numero di telefono del Cliente sono visibili agli altri membri; nella community su Skool sono visibili il nome, il profilo e i contenuti pubblicati dal Cliente, anche a iscritti che non partecipano al Programma. Skool, WhatsApp e Google trattano alcuni dati anche come titolari autonomi, secondo le proprie informative. Il Titolare non pubblica altrove i dati del Cliente.
**5. Trasferimenti fuori dall'Unione Europea.** Alcuni fornitori hanno sede o trattano dati fuori dall'Unione Europea, soprattutto negli Stati Uniti (per esempio Skool, Anthropic, Fathom, Notion, Cloudflare, Google, WhatsApp). Il trasferimento si fonda sulla decisione di adeguatezza della Commissione europea sul Data Privacy Framework (decisione di esecuzione (UE) 2023/1795) per i fornitori che vi aderiscono e, per gli altri o se quella decisione cessasse di applicarsi, sulle clausole contrattuali tipo della Commissione (decisione di esecuzione (UE) 2021/914) inserite nei contratti con i fornitori. Il Cliente può chiederne copia scrivendo a ${F.email}.
**6. Per quanto tempo.** Contratto, dati fiscali e prova della firma (compresi indirizzo IP e dispositivo): 10 anni dalla fine del contratto (artt. 2220 e 2946 c.c.). Dati dell'area clienti e informazioni condivise durante il Programma, comprese registrazioni, trascrizioni e riassunti delle chiamate individuali: fino alla fine del Programma e per i 12 mesi successivi, per l'assistenza e l'eventuale riattivazione dell'accesso; poi sono cancellati. Dati dell'invito e del modulo, se il contratto non viene firmato: 90 giorni dall'ultima attività o dall'annullamento dell'invito. Registrazioni delle chiamate di gruppo: visibili ai partecipanti per non oltre 24 mesi dalla registrazione, poi cancellate. In caso di contestazione i dati utili sono conservati fino alla sua definizione.
**7. I diritti del Cliente.** In ogni momento il Cliente può chiedere l'accesso ai propri dati, la rettifica, la cancellazione, la limitazione del trattamento e la portabilità, scrivendo a ${F.email}. **Diritto di opposizione:** il Cliente può opporsi in qualsiasi momento ai trattamenti fondati sul legittimo interesse (punti 3(b), 3(e) e 3(f)) scrivendo allo stesso indirizzo; per le registrazioni, il Titolare rimuove o oscura il passaggio che lo riguarda. Può revocare i consensi con la stessa facilità con cui li ha dati, senza effetti sui trattamenti già svolti. Può proporre reclamo al Garante per la protezione dei dati personali (www.garanteprivacy.it).
**8. Decisioni automatizzate.** Non vengono prese decisioni basate solo su trattamenti automatizzati che producano effetti giuridici sul Cliente. Gli strumenti di intelligenza artificiale del Sito producono documenti di lavoro e suggerimenti, che restano sotto il controllo del Titolare e del Cliente.
**9. Chi partecipa per conto di una società.** Se il Cliente è una società, i dati della persona che seguirà il Programma, quando è diversa da chi firma, sono forniti dalla società, che la informa consegnandole questa informativa; per quella persona valgono finalità, basi giuridiche, tempi di conservazione e diritti qui descritti.
`);
}
